### ISSUE TITLE
Generate Drush site YAML file

### ISSUE THREAD

**Issue by lpeabody** [digitalpolygon/polymer-pantheon-drupal#4]
For a given Pantheon site, add a command which will generate Drush site YAML. Example:

```yaml
'*':
  host: appserver.${env-name}.aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa.drush.in
  paths:
    files: files
    private: files/private
  uri: ${env-name}-my-pantheon-site.pantheonsite.io
  user: ${env-name}.aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa
  ssh:
    options: '-p 2222 -o "AddressFamily inet"'
    tty: false

```
